spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: root
      database: 0
      connect-timeout: 5s
      lettuce:
        pool:
          enabled: true
          # 连接池中的最小空闲连接
          min-idle: 4
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池最大活动连接数（使用负值表示没有限制）
          max-active: 32
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
