spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_test?
      &serverTimezone=Asia/Shanghai
      &characterEncoding=utf-8
      &useUnincode=true
      &useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.pcdd.mysql.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
